/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author huynh
 */
public class PanelItemDuAn extends javax.swing.JPanel {

    /**
     * Creates new form PanelItemDuAn
     */
    public PanelItemDuAn(String maDA, String tenDA, double chiPhi, java.util.Date ngayBD) {
        initComponents();
        // Gán chuỗi bình thường
        lblMaDA.setText(maDA);
        lblTenDA.setText(tenDA);

        // Format Chi phí (double -> String có dấu phẩy)
        lblChiPhi.setText(String.format("%,.0f VNĐ", chiPhi));
        lblChiPhi.setForeground(Color.blue);
        ;

        // Format Ngày tháng (Date -> String "dd/MM/yyyy")
        if (ngayBD != null) {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            lblNgayBD.setText(sdf.format(ngayBD));
        } else {
            lblNgayBD.setText("Chưa bắt đầu");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenDA = new javax.swing.JLabel();
        lblMaDA = new javax.swing.JLabel();
        lblChiPhi = new javax.swing.JLabel();
        lblNgayBD = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 60));
        setLayout(new java.awt.GridLayout(1, 0));

        lblTenDA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTenDA.setText("Tên Dự Án");
        add(lblTenDA);

        lblMaDA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblMaDA.setText("Mã Dự Án");
        add(lblMaDA);

        lblChiPhi.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblChiPhi.setText("Chi Phí");
        add(lblChiPhi);

        lblNgayBD.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblNgayBD.setText("Ngày BĐ");
        add(lblNgayBD);

        btnEdit.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblChiPhi;
    private javax.swing.JLabel lblMaDA;
    private javax.swing.JLabel lblNgayBD;
    private javax.swing.JLabel lblTenDA;
    // End of variables declaration//GEN-END:variables
}