/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.NhanVien_DTO;
import GUI.Panel_Frame.PanelItemDuAn;
import GUI.Panel_Frame.PanelItemNhanVien;

public class SepGUI extends javax.swing.JFrame {

        private NhanVien_DTO user;

        // Sửa constructor để nhận tham số nv
        public SepGUI(NhanVien_DTO nv) {
                initComponents();
                this.user = nv; // Lưu lại

                // Setup giao diện cơ bản
                this.setSize(1280, 720);
                this.setLocationRelativeTo(null);

                // Hiển thị tên lên Header
                if (nv != null) {
                        xinChaoText.setText("Xin chào: " + nv.getHoTen());
                }
                loadDanhSachNV();
                loadDanhSachDuAn();
        }

        public SepGUI() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Header = new javax.swing.JPanel();
                tenCty = new javax.swing.JLabel();
                leftGroupHeader = new javax.swing.JPanel();
                dangXuatBtn = new javax.swing.JButton();
                xinChaoText = new javax.swing.JLabel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                nhanVien = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                thanhTimKiem = new javax.swing.JTextField();
                timKiem_btn = new javax.swing.JButton();
                chiNhanh_cbb = new javax.swing.JComboBox<>();
                add_btn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                panelDanhSach = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                thanhTimKiem1 = new javax.swing.JTextField();
                timKiem_btn1 = new javax.swing.JButton();
                chiNhanh_cbb1 = new javax.swing.JComboBox<>();
                addduan_btn1 = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                panelDanhSachDuAn = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                Header.setBackground(new java.awt.Color(0, 0, 153));
                Header.setPreferredSize(new java.awt.Dimension(1280, 100));

                tenCty.setBackground(new java.awt.Color(255, 0, 51));
                tenCty.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
                tenCty.setForeground(new java.awt.Color(255, 102, 0));
                tenCty.setText("ABC GROUP");

                leftGroupHeader.setBackground(new java.awt.Color(0, 0, 153));

                dangXuatBtn.setBackground(new java.awt.Color(255, 255, 255));
                dangXuatBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                dangXuatBtn.setText("Đăng xuất");
                dangXuatBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dangXuatBtnActionPerformed(evt);
                        }
                });

                xinChaoText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                xinChaoText.setForeground(new java.awt.Color(255, 255, 255));
                xinChaoText.setText("Xin chào + Tên Nhân Viên");

                javax.swing.GroupLayout leftGroupHeaderLayout = new javax.swing.GroupLayout(leftGroupHeader);
                leftGroupHeader.setLayout(leftGroupHeaderLayout);
                leftGroupHeaderLayout.setHorizontalGroup(
                                leftGroupHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(leftGroupHeaderLayout.createSequentialGroup()
                                                                .addContainerGap(56, Short.MAX_VALUE)
                                                                .addGroup(leftGroupHeaderLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(dangXuatBtn,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                158,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(xinChaoText,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                275,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));
                leftGroupHeaderLayout.setVerticalGroup(
                                leftGroupHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(leftGroupHeaderLayout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addComponent(xinChaoText,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(dangXuatBtn)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
                Header.setLayout(HeaderLayout);
                HeaderLayout.setHorizontalGroup(
                                HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(HeaderLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(tenCty,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                319,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(leftGroupHeader,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                HeaderLayout.setVerticalGroup(
                                HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(HeaderLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(tenCty,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                76, Short.MAX_VALUE)
                                                                .addContainerGap())
                                                .addComponent(leftGroupHeader,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));

                jPanel1.setBackground(new java.awt.Color(153, 153, 153));

                timKiem_btn.setText("Tìm kiếm");
                timKiem_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                timKiem_btnActionPerformed(evt);
                        }
                });

                chiNhanh_cbb
                                .setModel(new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Cơ sở 1", "Cơ sở 2 ", "Cơ sở 3" }));
                chiNhanh_cbb.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chiNhanh_cbbActionPerformed(evt);
                        }
                });

                add_btn.setText("Thêm");
                add_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                add_btnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(thanhTimKiem,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                467,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(timKiem_btn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                146,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                72,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(chiNhanh_cbb,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                163,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(57, 57, 57)
                                                                .addComponent(add_btn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                146,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(206, 206, 206)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(thanhTimKiem,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                43,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(timKiem_btn)
                                                                                .addComponent(chiNhanh_cbb,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(add_btn))
                                                                .addContainerGap()));

                panelDanhSach.setLayout(new javax.swing.BoxLayout(panelDanhSach, javax.swing.BoxLayout.Y_AXIS));
                jScrollPane1.setViewportView(panelDanhSach);

                javax.swing.GroupLayout nhanVienLayout = new javax.swing.GroupLayout(nhanVien);
                nhanVien.setLayout(nhanVienLayout);
                nhanVienLayout.setHorizontalGroup(
                                nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1));
                nhanVienLayout.setVerticalGroup(
                                nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(nhanVienLayout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                504, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Xem Nhân Viên", nhanVien);

                jPanel3.setBackground(new java.awt.Color(153, 153, 153));

                timKiem_btn1.setText("Tìm kiếm");
                timKiem_btn1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                timKiem_btn1ActionPerformed(evt);
                        }
                });

                chiNhanh_cbb1
                                .setModel(new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Cơ sở 1", "Cơ sở 2 ", "Cơ sở 3" }));
                chiNhanh_cbb1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chiNhanh_cbb1ActionPerformed(evt);
                        }
                });

                addduan_btn1.setText("Thêm");
                addduan_btn1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {

                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(thanhTimKiem1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                467,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(timKiem_btn1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                146,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                72,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(chiNhanh_cbb1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                163,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(57, 57, 57)
                                                                .addComponent(addduan_btn1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                146,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(206, 206, 206)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(thanhTimKiem1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                43,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(timKiem_btn1)
                                                                                .addComponent(chiNhanh_cbb1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(addduan_btn1))
                                                                .addContainerGap()));

                panelDanhSachDuAn.setLayout(new javax.swing.BoxLayout(panelDanhSachDuAn, javax.swing.BoxLayout.Y_AXIS));
                jScrollPane2.setViewportView(panelDanhSachDuAn);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                516,
                                                                                Short.MAX_VALUE)));

                jTabbedPane1.addTab("Xem Dự Án", jPanel2);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 1287, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 595, Short.MAX_VALUE));

                jTabbedPane1.addTab("Thống Kê", jPanel4);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 1292,
                                                                Short.MAX_VALUE)
                                                .addComponent(jTabbedPane1));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Header,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTabbedPane1)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {
                // 1. Tạo một cửa sổ Dialog mới (Cửa sổ con)
                javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Thêm Nhân Viên Mới", true);

                // 2. Tạo PanelAddNhanVien và bỏ vào Dialog
                GUI.Panel_Frame.PanelAddNhanVien panel = new GUI.Panel_Frame.PanelAddNhanVien(dialog);
                dialog.getContentPane().add(panel);

                // 3. Setup kích thước và hiển thị
                dialog.pack(); // Tự động co giãn theo kích thước Panel
                dialog.setLocationRelativeTo(null); // Ra giữa màn hình
                dialog.setVisible(true);

                // 4. Khi Dialog đóng lại thì load lại danh sách bên ngoài
                loadDanhSachNV();
        }

        private void timKiem_btn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_timKiem_btn1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_timKiem_btn1ActionPerformed

        private void chiNhanh_cbb1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chiNhanh_cbb1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_chiNhanh_cbb1ActionPerformed

        private void chiNhanh_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chiNhanh_cbbActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_chiNhanh_cbbActionPerformed

        // dang xuat
        private void dangXuatBtnActionPerformed(java.awt.event.ActionEvent evt) {
                // 1. Hiện bảng hỏi: "Bạn có chắc không?"
                int luaChon = javax.swing.JOptionPane.showConfirmDialog(
                                this,
                                "Bạn có chắc chắn muốn đăng xuất?",
                                "Xác nhận đăng xuất",
                                javax.swing.JOptionPane.YES_NO_OPTION);

                // 2. Xử lý kết quả
                if (luaChon == javax.swing.JOptionPane.YES_OPTION) {
                        // Đóng cửa sổ Sếp lại (Giải phóng Ram)
                        this.dispose();

                        // Mở lại màn hình Đăng Nhập
                        new DangNhap().setVisible(true);
                }
        }

        private void loadDanhSachNV() {
                // 1. Lấy dữ liệu
                DAO.NhanVienDAO dao = new DAO.NhanVienDAO();
                java.util.ArrayList<DTO.NhanVien_DTO> list = dao.layDanhSachNhanVien();

                // 2. Xóa trắng danh sách cũ (tránh bị lặp khi reload)
                panelDanhSach.removeAll();

                // 3. Dùng vòng lặp tạo từng dòng
                for (DTO.NhanVien_DTO nv : list) {
                        // Truyền getVaiTro() vào tham số thứ 3
                        PanelItemNhanVien item = new PanelItemNhanVien(nv.getMaNV(), nv.getHoTen(), nv.getVaiTro());

                        panelDanhSach.add(item);
                        panelDanhSach.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
                }

                // 4. Vẽ lại giao diện (Bắt buộc)
                panelDanhSach.revalidate();
                panelDanhSach.repaint();
        }

        private void loadDanhSachDuAn() {
                // 1. Gọi BUS lấy dữ liệu (Đảm bảo bạn đã viết DuAnBUS và DuAnDAO nhé)
                BUS.DuAnBUS bus = new BUS.DuAnBUS();
                java.util.ArrayList<DTO.DuAn_DTO> list = bus.layToanBoDuAn();

                if (panelDanhSachDuAn == null)
                        return; // Đề phòng lỗi chưa tạo UI

                // 2. Xóa trắng danh sách cũ
                panelDanhSachDuAn.removeAll();

                // 3. Đổ dữ liệu vào
                for (DTO.DuAn_DTO da : list) {
                        // Truyền dữ liệu vào khuôn đúc
                        PanelItemDuAn item = new PanelItemDuAn(
                                        da.getMaDA(),
                                        da.getTenDA(),
                                        da.getDoanhThu(),
                                        da.getKinhPhi(),
                                        da.getNgayBatDau());

                        panelDanhSachDuAn.add(item);
                        panelDanhSachDuAn.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
                }

                // 4. Vẽ lại giao diện
                panelDanhSachDuAn.revalidate();
                panelDanhSachDuAn.repaint();
        }

        private void timKiem_btnActionPerformed(java.awt.event.ActionEvent evt) {
                // 1. Lấy từ khóa người dùng nhập
                String tuKhoa = thanhTimKiem.getText();

                // 2. Đưa cho BUS xử lý
                BUS.NhanVienBUS bus = new BUS.NhanVienBUS();
                java.util.ArrayList<DTO.NhanVien_DTO> ketQua = bus.timKiem(tuKhoa);

                // 3. Xóa giao diện cũ
                panelDanhSach.removeAll();

                // 4. Đổ danh sách kết quả mới vào
                for (DTO.NhanVien_DTO nv : ketQua) {
                        PanelItemNhanVien item = new PanelItemNhanVien(nv.getMaNV(), nv.getHoTen(), nv.getVaiTro());
                        panelDanhSach.add(item);
                        panelDanhSach.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
                }

                // 5. Cập nhật lại màn hình
                panelDanhSach.add(javax.swing.Box.createVerticalGlue());
                panelDanhSach.revalidate();
                panelDanhSach.repaint();
        }

        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SepGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SepGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SepGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SepGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new SepGUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel Header;
        private javax.swing.JButton add_btn;
        private javax.swing.JButton addduan_btn1;
        private javax.swing.JComboBox<String> chiNhanh_cbb;
        private javax.swing.JComboBox<String> chiNhanh_cbb1;
        private javax.swing.JButton dangXuatBtn;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JPanel leftGroupHeader;
        private javax.swing.JPanel nhanVien;
        private javax.swing.JPanel panelDanhSach;
        private javax.swing.JPanel panelDanhSachDuAn;
        private javax.swing.JLabel tenCty;
        private javax.swing.JTextField thanhTimKiem;
        private javax.swing.JTextField thanhTimKiem1;
        private javax.swing.JButton timKiem_btn;
        private javax.swing.JButton timKiem_btn1;
        private javax.swing.JLabel xinChaoText;
        // End of variables declaration//GEN-END:variables
}
