/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

/**
 *
 * @author huynh
 */
public class PanelItemNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form PanelItemNhanVien
     */
    // SỬA DÒNG NÀY: Thêm tham số vào trong ngoặc đơn
    public PanelItemNhanVien(String ma, String ten, String cn) {
        initComponents();

        // Bây giờ code mới hiểu ma, ten, cn là gì để gán vào
        lblMaNV.setText(ma);
        lblTenNV.setText(ten);
        lblChiNhanh.setText(cn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTenNV = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblChiNhanh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(516, 35));
        setPreferredSize(new java.awt.Dimension(800, 40));
        setLayout(new java.awt.GridLayout(1, 0));

        lblTenNV.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTenNV.setText("Tên Nhân Viên");
        add(lblTenNV);

        lblMaNV.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblMaNV.setText("Mã Nhân Viên");
        add(lblMaNV);

        lblChiNhanh.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblChiNhanh.setText("Chức vụ");
        add(lblChiNhanh);

        jPanel2.setLayout(new java.awt.GridLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eye-30.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(106, 106));
        jPanel2.add(jButton1);

        btnEdit.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblTenNV;
    // End of variables declaration//GEN-END:variables
}
