/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author huynh
 */
public class PanelDetailsDuAn extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetailsNhanVien
     */
    public PanelDetailsDuAn(String maNV) {
        initComponents();
        loadData(maNV);
    }

    private void loadData(String maDA) {
        // Gọi lớp BUS
        BUS.DuAnBUS bus = new BUS.DuAnBUS();

        // Gọi hàm getChiTietDuAn và truyền trực tiếp biến maDA vào
        DTO.DuAn_DTO da = bus.getChiTietDuAn(maDA);

        // 2. Nếu tìm thấy dự án thì tiến hành gán lên các Label
        if (da != null) {
            // Gán dữ liệu văn bản bình thường
            lbTenDA.setText(da.getTenDA() != null ? da.getTenDA().toUpperCase() : "CHƯA CÓ TÊN");
            lbMaDA.setText(da.getMaDA());

            // Gộp Chi nhánh và Phòng ban lại cho rõ ràng (ví dụ: CN01 - Kế Toán)
            String chiNhanhInfo = "N/A";
            if (da.getDanhSachMaCN() != null && !da.getDanhSachMaCN().isEmpty()) {
                chiNhanhInfo = String.join(", ", da.getDanhSachMaCN());
            }
            lbChiNhanh.setText(chiNhanhInfo);

            // Gán và định dạng Tiền tệ
            DecimalFormat df = new DecimalFormat("###,###,### VNĐ");
            lbKP.setText(df.format(da.getKinhPhi()));
            lbDT.setText(df.format(da.getDoanhThu()));

            // Gán và định dạng Ngày tháng
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date ngayBD = da.getNgayBatDau();
            Date ngayKT = da.getNgayKetThuc();

            if (ngayBD != null) {
                lbNBD.setText(sdf.format(ngayBD));
            } else {
                lbNBD.setText("Chưa xác định");
            }

            if (ngayKT != null) {
                lbNKT.setText(sdf.format(ngayKT));
            } else {
                lbNKT.setText("Chưa xác định");
            }

            // XỬ LÝ LOGIC TRẠNG THÁI DỰ ÁN
            // Ưu tiên 1: Kiểm tra xem dự án đã bị kết thúc sớm (Xóa mềm) trong CSDL chưa
            // SỬA LỖI: Thêm kiểm tra != null và dùng .trim() để loại bỏ các khoảng trắng dư
            // thừa do SQL sinh ra
            if (da.getTrangThai() != null && da.getTrangThai().trim().equalsIgnoreCase("Đã kết thúc")) {

                lbTrangThai.setText("Đã kết thúc");
                lbTrangThai.setForeground(new java.awt.Color(255, 0, 0)); // Chữ màu Đỏ rực

            } else {
                // Ưu tiên 2: Nếu chưa bị ép kết thúc, mới tự động tính toán theo ngày tháng
                Date homNay = new Date();

                if (ngayKT != null && homNay.after(ngayKT)) {
                    // Nếu hôm nay đã qua ngày kết thúc -> Hoàn thành
                    lbTrangThai.setText("Đã hoàn thành");
                    lbTrangThai.setForeground(new java.awt.Color(0, 153, 51)); // Chữ màu Xanh lá

                } else if (ngayBD != null && homNay.before(ngayBD)) {
                    // Nếu hôm nay chưa tới ngày bắt đầu -> Chưa bắt đầu
                    lbTrangThai.setText("Chưa bắt đầu");
                    lbTrangThai.setForeground(new java.awt.Color(153, 153, 153)); // Chữ màu Xám

                } else {
                    // Nằm trong khoảng thời gian diễn ra dự án
                    lbTrangThai.setText("Đang thực hiện");
                    lbTrangThai.setForeground(new java.awt.Color(255, 153, 0)); // Chữ màu Cam
                }
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu dự án này!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbTenDA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbMaDA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbChiNhanh = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbTrangThai = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbNBD = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbNKT = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbKP = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbDT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN DỰ ÁN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbTenDA.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTenDA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTenDA.setText("txtTenDA");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Mã dự án : ");

        lbMaDA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbMaDA.setText("lbMaDA");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Chi nhánh :");

        lbChiNhanh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbChiNhanh.setText("lbChiNhanh");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Trạng thái");

        lbTrangThai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbTrangThai.setText("lbTrangThai");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Ngày bắt đầu :");

        lbNBD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbNBD.setText("lbNBD");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Ngày kết thúc :");

        lbNKT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbNKT.setText("lbNKT");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Kinh phí :");

        lbKP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbKP.setText("lbKP");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Doanh thu :");

        lbDT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbDT.setText("lbDT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbMaDA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(lbChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbKP, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNBD, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNKT, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDT, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTenDA, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbTenDA)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbMaDA))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbChiNhanh))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbTrangThai))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbNBD))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbNKT))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbKP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDT)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbChiNhanh;
    private javax.swing.JLabel lbDT;
    private javax.swing.JLabel lbKP;
    private javax.swing.JLabel lbMaDA;
    private javax.swing.JLabel lbNBD;
    private javax.swing.JLabel lbNKT;
    private javax.swing.JLabel lbTenDA;
    private javax.swing.JLabel lbTrangThai;
    // End of variables declaration//GEN-END:variables
}
