/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author huynh
 */
public class PanelEditDuAn extends javax.swing.JPanel {

        /**
         * Creates new form PanelEditNhanVien
         */
        public String maDACS;
        private DTO.DuAn_DTO da;
        private javax.swing.JDialog parentDialog;

        public PanelEditDuAn(javax.swing.JDialog parent, String maDA) {
                this.parentDialog = parent;
                this.maDACS = maDA;
                initComponents();

                // Load dữ liệu ban đầu

                // 1. KHÓA CHỈNH SỬA MÃ DỰ ÁN VÀ TRẠNG THÁI
                txtMaDA.setEditable(false);
                txtTrangThaiDA.setEditable(false); // Trạng thái nên để hệ thống tự tính dựa vào ngày

                // 2. Load danh sách chi nhánh vào cmbCN trước
                // loadChiNhanh();

                // 3. Load thông tin chi tiết của dự án lên giao diện
                loadData();

        }

        // 4. LOAD DỮ LIỆU NHÂN VIÊN LÊN FORM

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtTenDA = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                txtMaDA = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                btnContinue = new javax.swing.JButton();
                cmbNBD = new de.wannawork.jcalendar.JCalendarComboBox();
                cmbNKT = new de.wannawork.jcalendar.JCalendarComboBox();
                txtKinhPhi = new javax.swing.JTextField();
                txtDoanhThu = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                txtTrangThaiDA = new javax.swing.JTextField();
                jCheckBox1 = new javax.swing.JCheckBox();
                jCheckBox2 = new javax.swing.JCheckBox();
                jCheckBox3 = new javax.swing.JCheckBox();

                setPreferredSize(new java.awt.Dimension(900, 440));

                jPanel1.setBackground(new java.awt.Color(102, 102, 102));

                jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("CHỈNH SỬA DỰ ÁN ");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                280,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Tên Dự Án");
                jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                txtTenDA.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
                txtTenDA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel2)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(txtTenDA,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                831,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtTenDA,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel6.setText("Chi nhánh :");

                jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel7.setText("Trạng thái");

                txtMaDA.setText("txtMaDA");

                jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel8.setText("Mã dự án");

                btnContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tick-100.png"))); // NOI18N
                btnContinue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                btnContinue.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnContinueActionPerformed(evt);
                        }
                });

                txtKinhPhi.setText("txtKinhPhi");

                txtDoanhThu.setText("txtDoanhThu");

                jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel9.setText("Doanh thu");

                jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel10.setText("Kinh phí");

                jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel11.setText("Ngày bắt đầu");

                jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel12.setText("Ngày kết thúc");

                txtTrangThaiDA.setText("txtTrangThai");
                txtTrangThaiDA.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtTrangThaiDAActionPerformed(evt);
                        }
                });

                jCheckBox1.setText("CN_HCM");
                jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBox1ActionPerformed(evt);
                        }
                });

                jCheckBox2.setText("CN_HN");
                jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBox2ActionPerformed(evt);
                        }
                });

                jCheckBox3.setText("CN_DN");
                jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBox3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 69, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel6,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel8,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(txtMaDA,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                138,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                                .addComponent(jCheckBox1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jCheckBox2,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jCheckBox3,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel11,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                100,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel10,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addGroup(layout
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                                false)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                txtDoanhThu)
                                                                                                                                                                                                .addComponent(cmbNBD,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                164,
                                                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                                                .addComponent(jLabel9,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                100,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addComponent(txtKinhPhi,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                164,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGap(105, 105,
                                                                                                                                                                                105)
                                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                false)
                                                                                                                                                                                .addComponent(cmbNKT,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(jLabel12,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                100,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addComponent(btnContinue,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                162,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                                .addContainerGap(
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(txtTrangThaiDA,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                138,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel7,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel8)
                                                                                                .addGap(9, 9, 9))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(jLabel12)
                                                                                                                                .addComponent(jLabel11))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(txtMaDA,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(cmbNBD,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(cmbNKT,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel6))
                                                                                .addComponent(jLabel10))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(txtKinhPhi,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jCheckBox1)))
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(17, 17, 17)
                                                                                                                                .addComponent(jLabel9)
                                                                                                                                .addGap(25, 25, 25))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jCheckBox2)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(txtDoanhThu,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                .addComponent(jCheckBox3))))))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(11, 11, 11)
                                                                                                .addComponent(btnContinue,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                67,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txtTrangThaiDA,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(28, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jCheckBox1ActionPerformed

        private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jCheckBox2ActionPerformed

        private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jCheckBox3ActionPerformed

        private void txtTrangThaiDAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTrangThaiDAActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtTrangThaiDAActionPerformed

        private void loadData() {
                BUS.DuAnBUS bus = new BUS.DuAnBUS();

                // Gán trực tiếp vào biến 'da' của class, không khai báo mới
                this.da = bus.getChiTietDuAn(maDACS);

                if (this.da != null) {
                        txtMaDA.setText(da.getMaDA());
                        txtTenDA.setText(da.getTenDA());

                        txtKinhPhi.setText(String.format("%.0f", da.getKinhPhi()));
                        txtDoanhThu.setText(String.format("%.0f", da.getDoanhThu()));

                        if (da.getNgayBatDau() != null)
                                cmbNBD.setDate(da.getNgayBatDau());
                        if (da.getNgayKetThuc() != null)
                                cmbNKT.setDate(da.getNgayKetThuc());

                        // Tích sẵn Checkbox - Phần này Thiện viết rất chuẩn rồi
                        java.util.List<String> listCN = da.getDanhSachMaCN();
                        System.out.println("Danh sách chi nhánh lấy được từ Database: " + listCN);
                        if (listCN != null) {

                                java.util.List<String> listClean = new java.util.ArrayList<>();
                                for (String s : listCN) {
                                        listClean.add(s.trim()); // Hàm trim() giúp xóa dấu cách thừa
                                }
                                jCheckBox1.setSelected(listClean.contains("CN_HCM"));
                                jCheckBox2.setSelected(listClean.contains("CN_HN"));
                                jCheckBox3.setSelected(listClean.contains("CN_DN"));
                        }

                        // Tính toán trạng thái hiển thị
                        java.util.Date homNay = new java.util.Date();
                        if (da.getNgayKetThuc() != null && homNay.after(da.getNgayKetThuc())) {
                                txtTrangThaiDA.setText("Đã hoàn thành");
                        } else if (da.getNgayBatDau() != null && homNay.before(da.getNgayBatDau())) {
                                txtTrangThaiDA.setText("Chưa bắt đầu");
                        } else {
                                txtTrangThaiDA.setText("Đang thực hiện");
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu dự án!");
                }
        }

        private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {
                // 1. Xác nhận trước khi lưu
                int confirm = JOptionPane.showConfirmDialog(this,
                                "Bạn có chắc chắn muốn lưu thay đổi dự án này?", "Xác nhận", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) {
                        return;
                }

                try {
                        // 2. Gom danh sách chi nhánh từ CheckBox TRƯỚC
                        java.util.List<String> danhSachCN = new java.util.ArrayList<>();
                        if (jCheckBox1.isSelected())
                                danhSachCN.add("CN_HCM");
                        if (jCheckBox2.isSelected())
                                danhSachCN.add("CN_HN");
                        if (jCheckBox3.isSelected())
                                danhSachCN.add("CN_DN");

                        if (danhSachCN.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Dự án phải thuộc ít nhất 1 chi nhánh!");
                                return;
                        }

                        // 3. Cập nhật dữ liệu vào đối tượng 'da' (Dùng biến của class)
                        if (this.da == null)
                                this.da = new DTO.DuAn_DTO(); // Phòng hờ lỗi null

                        this.da.setMaDA(txtMaDA.getText().trim());
                        this.da.setTenDA(txtTenDA.getText().trim());
                        this.da.setKinhPhi(Double.parseDouble(txtKinhPhi.getText().trim()));
                        this.da.setDoanhThu(Double.parseDouble(txtDoanhThu.getText().trim()));
                        this.da.setNgayBatDau(cmbNBD.getDate());
                        this.da.setNgayKetThuc(cmbNKT.getDate());
                        this.da.setDanhSachMaCN(danhSachCN);
                        this.da.setTrangThai("DangChay"); // Hoặc lấy từ logic tính toán của bạn

                        // 4. Gọi hàm BUS sau khi đã có đầy đủ dữ liệu
                        BUS.DuAnBUS bus = new BUS.DuAnBUS();
                        boolean ketQua = bus.capNhatDuAn(this.da);

                        if (ketQua) {
                                JOptionPane.showMessageDialog(this, "Cập nhật dự án thành công!");
                                if (this.parentDialog != null) {
                                        this.parentDialog.dispose();
                                }
                        } else {
                                JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại!", "Lỗi",
                                                JOptionPane.ERROR_MESSAGE);
                        }

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Lỗi: Kinh phí và Doanh thu phải là số!", "Lỗi nhập liệu",
                                        JOptionPane.WARNING_MESSAGE);
                } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Có lỗi hệ thống: " + e.getMessage(), "Lỗi",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_fieldNameActionPerformed

        private void maPB_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maPB_cbbActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_maPB_cbbActionPerformed

        private void chiNhanh_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chiNhanh_cbbActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_chiNhanh_cbbActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnContinue;
        private de.wannawork.jcalendar.JCalendarComboBox cmbNBD;
        private de.wannawork.jcalendar.JCalendarComboBox cmbNKT;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JCheckBox jCheckBox2;
        private javax.swing.JCheckBox jCheckBox3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JTextField txtDoanhThu;
        private javax.swing.JTextField txtKinhPhi;
        private javax.swing.JTextField txtMaDA;
        private javax.swing.JTextField txtTenDA;
        private javax.swing.JTextField txtTrangThaiDA;
        // End of variables declaration//GEN-END:variables
}
