/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

/**
 *
 * @author huynh
 */
public class PanelThongKeDuAn extends javax.swing.JPanel {

    /**
     * Creates new form PanelThongKeDuAn
     */
    public PanelThongKeDuAn(String maDA, String tenDA, String tenPB, String chiSo) {
        initComponents();

        // 1. Gán dữ liệu
        lblMaDA.setText(maDA);
        lblTenDA.setText(tenDA);
        lblTenPB.setText(tenPB);
        lblChiSoDA.setText(chiSo);

        // 2. PHÁ BỎ BỐ CỤC CŨ CỦA NETBEANS
        this.removeAll();

        // Tạo một Panel phụ chứa 4 chữ, chia 4 cột đều nhau
        javax.swing.JPanel pnlText = new javax.swing.JPanel(new java.awt.GridLayout(1, 4));
        pnlText.setBackground(java.awt.Color.WHITE);
        pnlText.add(lblMaDA);
        pnlText.add(lblTenDA);
        pnlText.add(lblTenPB);
        pnlText.add(lblChiSoDA);

        // Đặt Panel chữ ở giữa, Nút bấm ở sát lề phải
        this.setLayout(new java.awt.BorderLayout());
        this.add(pnlText, java.awt.BorderLayout.CENTER);
        this.add(TTDuAn_btn, java.awt.BorderLayout.EAST);

        // 3. CĂN LỀ CHỮ
        lblMaDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenDA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenPB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChiSoDA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblTenDA.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lblChiSoDA.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 15));

        // 4. CÔNG THỨC KÍCH THƯỚC MỀM (Chống tràn, chống cắt)
        this.setMaximumSize(new java.awt.Dimension(32767, 40));
        this.setPreferredSize(new java.awt.Dimension(10, 40));
        this.setMinimumSize(new java.awt.Dimension(0, 40));

        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 200, 200)));
        this.setBackground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMaDA = new javax.swing.JLabel();
        lblTenDA = new javax.swing.JLabel();
        lblTenPB = new javax.swing.JLabel();
        lblChiSoDA = new javax.swing.JLabel();
        TTDuAn_btn = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 40));

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 40));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        lblMaDA.setText("Tên Nhân viên");
        jPanel2.add(lblMaDA);

        lblTenDA.setText("jLabel1");
        jPanel2.add(lblTenDA);

        lblTenPB.setText("Tên phòng ban đảm nhiệm");
        jPanel2.add(lblTenPB);

        lblChiSoDA.setText("chi so ");
        jPanel2.add(lblChiSoDA);

        TTDuAn_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eye-24.png"))); // NOI18N
        jPanel2.add(TTDuAn_btn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 700, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TTDuAn_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChiSoDA;
    private javax.swing.JLabel lblMaDA;
    private javax.swing.JLabel lblTenDA;
    private javax.swing.JLabel lblTenPB;
    // End of variables declaration//GEN-END:variables
}
