/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author huynh
 */
public class PanelAddDuAn extends javax.swing.JPanel {

    /**
     * Creates new form PanelEditNhanVien
     */
    public String maDACS;
    private javax.swing.JDialog parentDialog;
    String maDa;

    public PanelAddDuAn(javax.swing.JDialog parent) {
        this.parentDialog = parent;
        this.maDACS = maDACS;
        initComponents();

        // Load dữ liệu ban đầu

        initComponents();

        // 1. KHÓA CHỈNH SỬA MÃ DỰ ÁN VÀ TRẠNG THÁI

        // 2. Load danh sách chi nhánh vào cmbCN trước
        loadChiNhanh();

        // 3. Load thông tin chi tiết của dự án lên giao diện

    }

    // 4. LOAD DỮ LIỆU NHÂN VIÊN LÊN FORM

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        cmbNBD = new de.wannawork.jcalendar.JCalendarComboBox();
        cmbNKT = new de.wannawork.jcalendar.JCalendarComboBox();
        txtKinhPhi = new javax.swing.JTextField();
        txtDoanhThu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbChiNhanh = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(417, 375));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thêm Dự Án");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên Dự Án");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtTenDA.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTenDA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addContainerGap(323, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtTenDA)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenDA, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Chi nhánh :");

        btnContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tick-100.png"))); // NOI18N
        btnContinue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        txtKinhPhi.setText("txtKinhPhi");

        txtDoanhThu.setText("txtDoanhThu");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Doanh thu");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Ngày bắt đầu");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Ngày kết thúc");

        cmbChiNhanh.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Kinh phí");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbNBD, javax.swing.GroupLayout.DEFAULT_SIZE, 138,
                                                Short.MAX_VALUE)
                                        .addComponent(cmbNKT, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbChiNhanh, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(btnContinue,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 162,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtKinhPhi,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel13,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtDoanhThu,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 162,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 5, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 29, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbNBD, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbNKT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));
    }// </editor-fold>//GEN-END:initComponents

    private void loadChiNhanh() {
        BUS.NhanVienBUS bus = new BUS.NhanVienBUS();
        cmbChiNhanh.removeAllItems();

        // Lấy danh sách mã chi nhánh từ database nạp vào ComboBox
        for (String cn : bus.getListMaCN()) {
            cmbChiNhanh.addItem(cn);
        }
    }

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnContinueActionPerformed

        // 1. Kiểm tra dữ liệu rỗng (Validation cơ bản)
        if (txtTenDA.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên dự án!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            BUS.DuAnBUS bus = new BUS.DuAnBUS();
            DTO.DuAn_DTO daMoi = new DTO.DuAn_DTO();

            // 2. TỰ ĐỘNG SINH MÃ DỰ ÁN
            String maMoi = bus.taoMaDuAnMoi();
            daMoi.setMaDA(maMoi);

            // 3. Lấy thông tin từ giao diện
            daMoi.setTenDA(txtTenDA.getText().trim());

            // Xử lý kiểu số (Kinh phí, Doanh thu) - Mặc định là 0 nếu để trống
            String strKinhPhi = txtKinhPhi.getText().trim();
            daMoi.setKinhPhi(strKinhPhi.isEmpty() ? 0 : Double.parseDouble(strKinhPhi));

            String strDoanhThu = txtDoanhThu.getText().trim();
            daMoi.setDoanhThu(strDoanhThu.isEmpty() ? 0 : Double.parseDouble(strDoanhThu));

            // Lấy ngày từ JCalendarComboBox
            daMoi.setNgayBatDau(cmbNBD.getDate());
            daMoi.setNgayKetThuc(cmbNKT.getDate());

            // Lấy chi nhánh
            if (cmbChiNhanh.getSelectedItem() != null) {
                java.util.List<String> listCN = new java.util.ArrayList<>();
                listCN.add(cmbChiNhanh.getSelectedItem().toString());
                daMoi.setDanhSachMaCN(listCN);
            }

            // 4. GỌI BUS ĐỂ LƯU VÀO DATABASE
            boolean ketQua = bus.themDuAn(daMoi);

            if (ketQua) {
                JOptionPane.showMessageDialog(this, "Thêm dự án thành công!\nMã dự án mới là: " + maMoi, "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
                if (this.parentDialog != null) {
                    this.parentDialog.dispose(); // Đóng cửa sổ Thêm
                }
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại. Vui lòng kiểm tra lại!", "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi: Kinh phí và Doanh thu phải là số hợp lệ!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi hệ thống xảy ra: " + e.getMessage(), "Lỗi hệ thống",
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_btnContinueActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_fieldNameActionPerformed

    private void maPB_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maPB_cbbActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_maPB_cbbActionPerformed

    private void chiNhanh_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chiNhanh_cbbActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chiNhanh_cbbActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JComboBox<String> cmbChiNhanh;
    private de.wannawork.jcalendar.JCalendarComboBox cmbNBD;
    private de.wannawork.jcalendar.JCalendarComboBox cmbNKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDoanhThu;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtTenDA;
    // End of variables declaration//GEN-END:variables
}
