/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author huynh
 */
public class PanelEditDuAn extends javax.swing.JPanel {

    /**
     * Creates new form PanelEditNhanVien
     */
    public String maDACS;
    private javax.swing.JDialog parentDialog;

    public PanelEditDuAn(javax.swing.JDialog parent, String maDA) {
        this.parentDialog = parent;
        this.maDACS = maDA;
        initComponents();

        // Load dữ liệu ban đầu

        initComponents();

        // 1. KHÓA CHỈNH SỬA MÃ DỰ ÁN VÀ TRẠNG THÁI
        txtMaDA.setEditable(false);
        txtTrangThaiDA.setEditable(false); // Trạng thái nên để hệ thống tự tính dựa vào ngày

        // 2. Load danh sách chi nhánh vào cmbCN trước
        loadChiNhanh();

        // 3. Load thông tin chi tiết của dự án lên giao diện
        loadData();

    }

    // 4. LOAD DỮ LIỆU NHÂN VIÊN LÊN FORM

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaDA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        cmbNBD = new de.wannawork.jcalendar.JCalendarComboBox();
        cmbNKT = new de.wannawork.jcalendar.JCalendarComboBox();
        txtKinhPhi = new javax.swing.JTextField();
        txtDoanhThu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTrangThaiDA = new javax.swing.JTextField();
        cmbChiNhanh = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(900, 400));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chỉnh Sửa Dự Án");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên Dự Án");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtTenDA.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTenDA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTenDA, javax.swing.GroupLayout.PREFERRED_SIZE, 831,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenDA, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Chi nhánh :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái");

        txtMaDA.setText("txtMaDA");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Mã dự án");

        btnContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tick-100.png"))); // NOI18N
        btnContinue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        txtKinhPhi.setText("txtKinhPhi");

        txtDoanhThu.setText("txtDoanhThu");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Doanh thu");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Kinh phí");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Ngày bắt đầu");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Ngày kết thúc");

        txtTrangThaiDA.setText("txtTrangThai");

        cmbChiNhanh.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaDA)
                                        .addComponent(cmbChiNhanh, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(txtTrangThaiDA, javax.swing.GroupLayout.DEFAULT_SIZE, 138,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addComponent(txtDoanhThu)
                                                                                        .addComponent(cmbNBD,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                164, Short.MAX_VALUE))
                                                                                .addGap(105, 105, 105))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel9,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                100,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(txtKinhPhi,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                164,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(105, 105, 105)))
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(cmbNKT,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnContinue,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                162,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(9, 9, 9))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtMaDA, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbNBD, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbNKT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6))
                                        .addComponent(jLabel10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtKinhPhi,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cmbChiNhanh,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel9))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtTrangThaiDA,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtDoanhThu,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(32, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void loadChiNhanh() {
        BUS.NhanVienBUS bus = new BUS.NhanVienBUS();
        cmbChiNhanh.removeAllItems();

        // Lấy danh sách mã chi nhánh từ database nạp vào ComboBox
        for (String cn : bus.getListMaCN()) {
            cmbChiNhanh.addItem(cn);
        }
    }

    private void loadData() {
        BUS.DuAnBUS bus = new BUS.DuAnBUS();
        DTO.DuAn_DTO da = bus.getChiTietDuAn(maDACS);

        if (da != null) {
            // Gán Text
            txtMaDA.setText(da.getMaDA());
            txtTenDA.setText(da.getTenDA());

            // Ép kiểu Kinh phí và Doanh thu thành chuỗi, bỏ phần thập phân
            txtKinhPhi.setText(String.format("%.0f", da.getKinhPhi()));
            txtDoanhThu.setText(String.format("%.0f", da.getDoanhThu()));

            // Gán Ngày tháng
            if (da.getNgayBatDau() != null) {
                cmbNBD.setDate(da.getNgayBatDau());
            }
            if (da.getNgayKetThuc() != null) {
                cmbNKT.setDate(da.getNgayKetThuc());
            }

            // Gán Chi nhánh
            if (da.getDanhSachMaCN() != null && !da.getDanhSachMaCN().isEmpty()) {
                cmbChiNhanh.setSelectedItem(da.getDanhSachMaCN().get(0));
            }

            // Tự động tính toán Trạng thái để hiển thị
            Date homNay = new Date();
            Date ngayBD = da.getNgayBatDau();
            Date ngayKT = da.getNgayKetThuc();

            if (ngayKT != null && homNay.after(ngayKT)) {
                txtTrangThaiDA.setText("Đã hoàn thành");
            } else if (ngayBD != null && homNay.before(ngayBD)) {
                txtTrangThaiDA.setText("Chưa bắt đầu");
            } else {
                txtTrangThaiDA.setText("Đang thực hiện");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu của dự án này!");
        }
    }

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
        // 1. Xác nhận trước khi lưu
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn lưu thay đổi dự án này?", "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return; // Nếu người dùng chọn "No" thì dừng lại
        }

        try {
            // 2. Lấy toàn bộ thông tin từ giao diện
            String ma = txtMaDA.getText().trim();
            String ten = txtTenDA.getText().trim();

            // Xử lý kiểu số (Kinh phí, Doanh thu)
            double kinhPhi = Double.parseDouble(txtKinhPhi.getText().trim());
            double doanhThu = Double.parseDouble(txtDoanhThu.getText().trim());

            // Lấy ngày từ JCalendarComboBox
            java.util.Date nbd = cmbNBD.getDate();
            java.util.Date nkt = cmbNKT.getDate();

            // Lấy chi nhánh
            java.util.List<String> danhSachCN = new java.util.ArrayList<>();
            if (cmbChiNhanh.getSelectedItem() != null) {
                danhSachCN.add(cmbChiNhanh.getSelectedItem().toString());
            }

            // 3. Đóng gói vào đối tượng DTO
            DTO.DuAn_DTO da = new DTO.DuAn_DTO();
            da.setMaDA(ma);
            da.setTenDA(ten);
            da.setKinhPhi(kinhPhi);
            da.setDoanhThu(doanhThu);
            da.setNgayBatDau(nbd);
            da.setNgayKetThuc(nkt);
            da.setDanhSachMaCN(danhSachCN);

            // 4. Gọi hàm BUS và kiểm tra
            BUS.DuAnBUS bus = new BUS.DuAnBUS();
            boolean ketQua = bus.capNhatDuAn(da);

            if (ketQua) {
                JOptionPane.showMessageDialog(this, "Cập nhật dự án thành công!");
                if (this.parentDialog != null) {
                    this.parentDialog.dispose(); // Đóng cửa sổ
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại!", "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi: Kinh phí và Doanh thu phải là số hợp lệ!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi hệ thống xảy ra: " + e.getMessage(), "Lỗi hệ thống",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnContinueActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_fieldNameActionPerformed

    private void maPB_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maPB_cbbActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_maPB_cbbActionPerformed

    private void chiNhanh_cbbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chiNhanh_cbbActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chiNhanh_cbbActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JComboBox<String> cmbChiNhanh;
    private de.wannawork.jcalendar.JCalendarComboBox cmbNBD;
    private de.wannawork.jcalendar.JCalendarComboBox cmbNKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDoanhThu;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtMaDA;
    private javax.swing.JTextField txtTenDA;
    private javax.swing.JTextField txtTrangThaiDA;
    // End of variables declaration//GEN-END:variables
}
