/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel_Frame;

import DTO.NhanVien_DTO;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author huynh
 */
public class PanelDetailsNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetailsNhanVien
     */
    public PanelDetailsNhanVien(String maNV) {
        initComponents();
        loadData(maNV);
    }

    private void loadData(String maNV) {
        BUS.NhanVienBUS bus = new BUS.NhanVienBUS();

        // Gọi hàm BUS -> DAO để lấy thông tin chi tiết
        NhanVien_DTO nv = bus.getChiTietNhanVien(maNV);

        if (nv != null) {
            // Gán các thông tin cơ bản
            manvLabel.setText(nv.getMaNV());

            // Tìm component tên là jLabel3 (Họ tên) trong code sinh ra hoặc gán nếu bạn đã
            // đổi tên biến
            // Trong file bạn gửi, tiêu đề là jLabel3 ("HUỲNH XUÂN THIỆN"), ta gán đè lên nó
            jLabel3.setText(nv.getHoTen().toUpperCase());

            gioiTinhLabel.setText(nv.getGioiTinh());

            // Xử lý Ngày sinh
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            if (nv.getNgaySinh() != null) {
                ngaySinhLabel.setText(sdf.format(nv.getNgaySinh()));
            } else {
                ngaySinhLabel.setText("Chưa cập nhật");
            }

            // Xử lý Lương (Format tiền Việt)
            NumberFormat vnCurrency = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
            luongLabel.setText(vnCurrency.format(nv.getLuong()));

            // Xử lý chức vụ, phòng ban, chi nhánh
            role_label.setText(nv.getVaiTro());
            chiNhanhLabel.setText(nv.getMaCN()); // Nếu muốn hiện tên Chi nhánh thì cần query thêm bảng ChiNhanh
            phongBanLabel.setText(nv.getMaPB());

            // Xử lý địa chỉ (Ghép chuỗi: Số nhà + Phường + Tỉnh)
            String diaChiFull = "";
            if (nv.getDcSoNha() != null)
                diaChiFull += nv.getDcSoNha() + ", ";
            if (nv.getDcPhuong() != null)
                diaChiFull += nv.getDcPhuong() + ", ";
            if (nv.getDcTinh() != null)
                diaChiFull += nv.getDcTinh();

            // Cắt dấu phẩy thừa ở cuối nếu có
            if (diaChiFull.endsWith(", ")) {
                diaChiFull = diaChiFull.substring(0, diaChiFull.length() - 2);
            }

            if (diaChiFull.isEmpty())
                diaChiFull = "Chưa cập nhật";
            address_label.setText(diaChiFull);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        manvLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gioiTinhLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chiNhanhLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phongBanLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ngaySinhLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        luongLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        role_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN NHÂN VIÊN ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("HUỲNH XUÂN THIỆN");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Mã NV : ");

        manvLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        manvLabel.setText("mã nhân viên");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Giới tính : ");

        gioiTinhLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        gioiTinhLabel.setText("Nam/ Nữ");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Chi nhánh :");

        chiNhanhLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chiNhanhLabel.setText("mã chi nhánh - tên chi nhánh ");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Phòng ban :");

        phongBanLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phongBanLabel.setText("mã phòng ban - tên phòng ban ");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Địa chỉ : ");

        address_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        address_label.setText("số nhà , + phường , +  tỉnh ");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Ngày sinh : ");

        ngaySinhLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ngaySinhLabel.setText("ngày sinh");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Lương hiện tại : ");

        luongLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        luongLabel.setText("lương");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Chúc vụ :");

        role_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        role_label.setText("Nhanvien / QuanLy / Sep");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(manvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(91, 91, 91)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 119,
                                                        Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gioiTinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(190, 190, 190))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(146, 146, 146)
                                                                .addComponent(chiNhanhLabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 252,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel16,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(luongLabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 718,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jLabel14,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel12,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel10,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                128, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(phongBanLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                252,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(address_label,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                686,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ngaySinhLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                718,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel18,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(role_label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 718,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(manvLabel)
                                        .addComponent(jLabel5)
                                        .addComponent(gioiTinhLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(chiNhanhLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(phongBanLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(address_label))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(ngaySinhLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(luongLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(role_label))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JLabel chiNhanhLabel;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel luongLabel;
    private javax.swing.JLabel manvLabel;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JLabel phongBanLabel;
    private javax.swing.JLabel role_label;
    // End of variables declaration//GEN-END:variables
}
